apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp-servicemonitor
  namespace: challenger-001
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: webapp
  namespaceSelector:
    matchNames:
      - challenger-001
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
