apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: challenger-001
  labels:
    app: webapp
spec:
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
  selector:
    app: webapp
